# Generated by Django 3.2.9 on 2022-01-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=255, verbose_name='Отчество')),
                ('pin', models.CharField(max_length=255, verbose_name='ПИН')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('plot', models.TextField(verbose_name='Фабула')),
                ('image', models.ImageField(default='media/', null=True, upload_to='media')),
                ('image1', models.ImageField(default='media/', null=True, upload_to='media')),
                ('image2', models.ImageField(default='media/', null=True, upload_to='media')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Добавить',
                'verbose_name_plural': 'Добавить данные',
            },
        ),
    ]
