# Generated by Django 3.2.9 on 2022-01-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Фото 3x4'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Фото в рост'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Фото с боку'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pin',
            field=models.CharField(max_length=255, unique=True, verbose_name='ПИН'),
        ),
    ]
