# Generated by Django 3.2.9 on 2022-01-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20220126_0520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Названия')),
                ('image', models.ImageField(null=True, upload_to='media', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Добавить',
                'verbose_name_plural': 'Добавить Иконку',
            },
        ),
    ]
