# Generated by Django 3.2.9 on 2022-01-27 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Icon',
        ),
    ]
