# Generated by Django 3.2.9 on 2022-02-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20220202_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Фото 3x4'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Фото в рост'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Фото с боку'),
        ),
    ]
